---
title: "Seurat_SCTransformation_Normalization"
author: "Kevin Green and Katie Prater"
date: "7/7/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, cache=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setenv(PATH="/acct/guest/.TinyTeX/bin:$PATH:")
library(Seurat)
library(Matrix)
library(ggplot2)
library(foreach)
library(doParallel)
library(stringr)
```

# Jayadev Lab RNAseq Data Processing Pipeline

## Define your project folders, filenames, and variables of interest.
# You MUST edit this for your dataset to run properly!!!!
```{r 'Project_Information', echo=TRUE}
#Document your code:
print("This is when this code was run:")
print(Sys.time())

#Do you want to downsample the dat for testing purposes
#Enter TRUE or FALSE
downsample <- TRUE

# Load data from snRNAseq_QC_code
load("thresholded_pu1_only.rdata")

# Create variable for qc_plots directory
plotspath <- file.path(projdir, outdir, "qc_plots", fsep = "/")

# Change suffix if needed
suffix <- "_pu1_only_test"

#Set the number of variable features to use 
nfeatures <- 2000

# Set the assay name post normalization ("RNA" or "SCT")
assay <- "SCT"

```

## Determine and graph thresholds for your dataset.
```{r QC_Plots}
# #QC metric histograms colored by sample with threshold lines plotted
 plot7 <-  ggplot(ss_data@meta.data,
                  aes(color=ss_data@meta.data$orig.ident,
                      x=nCount_RNA,
                      fill= ss_data@meta.data$orig.ident)) + 
   geom_density(alpha = 0.2) + 
   scale_x_log10() + 
   theme_classic() +
   xlab("Number of copies/gene") +
   ylab("Frequency") +
   geom_vline(xintercept = 400) ##Edit this value for your threshold of choice

plot8 <-  ggplot(ss_data@meta.data,
                 aes(color=ss_data@meta.data$orig.ident,
                     x=percent.mito,
                     fill= ss_data@meta.data$orig.ident)) +
  geom_density(alpha = 0.2) +
  scale_x_log10() +
  theme_classic() +
  xlab("% Mitochondrial Genes") +
  ylab("Frequency") +
  geom_vline(xintercept = 2.0) ##Edit this value for your threshold of choice

 plot9 <-  ggplot(ss_data@meta.data,
                  aes(color=ss_data@meta.data$orig.ident,
                      x=nFeature_RNA,
                      fill= ss_data@meta.data$orig.ident)) + 
   geom_density(alpha = 0.2) + 
   theme_classic() +
   scale_x_log10() +
   xlab("Number of genes/cell") +
   ylab("Frequency") +
   geom_vline(xintercept = 375) ##Edit this value for your threshold of choice
 
#Save the plots
png(paste0(plotspath, "/QC_feature_histograms_by_sample", suffix, ".png"),
    1800, 900)
CombinePlots(plots = list(plot7,plot8,plot9))
dev.off()
```

## Threshold the data based on the above QC thresholds that you set.
```{r Threshold_data}
###### You MUST modify these thresholds for your dataset. ########
ss_data_filtered <- subset(x = ss_data,
                           subset = nFeature_RNA >= 375 &
                             nCount_RNA >= 400 &
                             percent.mito < 2.0)

#Save the seurat objects after thresholding.
if(!downsample) {
  saveRDS(ss_data_filtered, file = paste0( "seurat_ss_data_thresholded", suffix, ".rds"))
}

rm(ss_data, list = setdiff(ls(pattern = "^plot"), "plotspath"))
```

## Normalize using Seurat SCTransform
```{r SCTransform, warning=FALSE}
#Downsampling for testing purposes
if(downsample) {
  ss_data_filtered <- subset(ss_data_filtered,
                       ident = unique(ss_data_filtered@meta.data[["orig.ident"]]),
                       downsample = 300)
}

#Split data into multiple chunks if too large to normalize at once
if (length(samples) > 7) {
  ss_data_filtered1 <- subset(x = ss_data_filtered, 
                           ident = c(samples[1:7]))
  saveRDS(ss_data_filtered1, file = paste0("seurat_ss_data_normalized", suffix, "_1.rds"))
  rm(ss_data_filtered1)
  ss_data_filtered2 <- subset(x = ss_data_filtered, 
                           ident = c(samples[8:length(samples)]))
  rm(ss_data_filtered)
  # Normalize read depth using SCTransformation
  ss_data_filtered2 <- Seurat::SCTransform(ss_data_filtered2,
                                           #new.assay.name = assay,
                                           variable.features.n = nfeatures,
                                           do.scale = FALSE,
                                           do.center = FALSE,
                                           conserve.memory = TRUE,
                                           return.only.var.genes = FALSE,
                                           #vars.to.regress = "percent.mito",
                                           verbose = FALSE)
  saveRDS(ss_data_filtered2, file = paste0("seurat_ss_data_normalized", suffix, "_2.rds"))
  rm(ss_data_filtered2)
  ss_data_filtered1 <- readRDS(paste0("seurat_ss_data_normalized", suffix, "_1.rds"))
  ss_data_filtered1 <- Seurat::SCTransform(ss_data_filtered1,
                                           #new.assay.name = assay,
                                           variable.features.n = nfeatures,
                                           do.scale = FALSE,
                                           do.center = FALSE,
                                           conserve.memory = TRUE,
                                           return.only.var.genes = FALSE,
                                           #vars.to.regress = "percent.mito",
                                           verbose = FALSE)
  saveRDS(ss_data_filtered1, file = paste0("seurat_ss_data_normalized", suffix, "_1.rds"))
  ss_data_filtered2 <- readRDS(paste0("seurat_ss_data_normalized", suffix, "_2.rds"))
  ss_data_filtered1 <- merge(ss_data_filtered1, ss_data_filtered2)
  ss_data_filtered <- ss_data_filtered1
  rm(ss_data_filtered1, ss_data_filtered2)
} else {
# Normalize read depth using SCTransformation
ss_data_filtered <- Seurat::SCTransform(ss_data_filtered,
                                        #new.assay.name = assay,
                                        variable.features.n = nfeatures,
                                        do.scale = FALSE,
                                        do.center = FALSE,
                                        conserve.memory = TRUE,
                                        return.only.var.genes = FALSE,
                                        #vars.to.regress = "percent.mito",
                                        verbose = TRUE)
}

#Save the seurat objects after thresholding.
save.image(file = paste0("normalized", suffix, ".rdata"), compress = TRUE)

```